### ISSUE TITLE
Initiating the tool with windows through task scheduler breaks function keys apparently

### ISSUE THREAD

**Issue by Rodrxx** [4JX/L5P-Keyboard-RGB#26] opened 2021-11-15 13:22 UTC
I just want to leave a experience with the app, maybe is just my fault, i wanted the app to run exactly at the time the machine turn on so i dont have to manually open it everytime i log in, so i created a task in task scheduler to open the app as soon as the machine boots up, before i log in (so i had to type administrator password to create the task).

Next time my machine booted up, apparently the function keys like brightness control, airplane mode, microphone, touchpad toggle and lenovo special key stopped working, also the status LED for the num lock key got stuck and it couldnt turn it off even if the num pad wasnt active, same goes for the caps lock, which was the opposite, it couldnt turn on even if the caps lock was active.

Volume keys, num lock, caps lock worked fine, and the Fn Lock in Esc key worked only if i turn it on through software, and i can even control the normal rgb as usual through the app and lenovo vantage software, the only thing broken was the rest of the Fn Keys and the Status LED on some.

Maybe it was just my bad but the only way to solve this problem, i had to do a factory reset, contacted lenovo support and they brought me a tool to reinstall windows from scratch, so the problem was solved there, a little advice to someone who could do the same, and this thing happened, so if anyone with their 5 pro could try this (if the issue exists you may have to factory reset the laptop using the lenovo recovery key to fix it) and confirm this issue since i dont want to factory reset my 5 pro again, so the dev can make a failsafe in this regard if that was the case or not because im dumb enough to do that kind of stuff

**Comment by 4JX** [comment] 2021-11-15 17:18
How exactly did you start the software? Did the task just open the GUI or start it with arguments via the command line?

In any case this doesn't sound like its a "this software" issue (***directly***). Generally if an app is able to cause system wide issues bad enough to warrant reinstalling the OS, the problem is with the rest of the system and not the app itself. This software only communicates with the part of the keyboard that touches light controls, so I'm having a hard time imagining how it could happen.

**Comment by Rodrxx** [comment] 2021-11-15 17:27
I just put the .exe in the task scheduler, select launch with high privileges at boot (because i wanted to initialize it just after the button press, otherwise it wont let me do it, as the other option was to launch it after i login into the desktop), i though the communication between the program and the keyboard went just before the official lenovo stuff and broke everything, im also curious on how it could happen, but i cant replicate it again, i mean, i can, but it is a total pain to reinstall everything if something goes wrong, and i dont have too much time to do it

**Comment by 4JX** [comment] 2021-11-15 17:35
Is there any specific reason you chose launching as soon as the laptop turned on rather than after logging in?

There's precisely one line of code in the program which I can suspect it could've at any point conflicted with Vantage or whatever other driver from Lenovo (which essentially does something like "I want to establish a connection with the keyboard" "here I am here's your connection"). I'll see what can be done about it, but this sounds more like a "Lenovo did not account for this being something that could happen in their code" (fair enough for them) issue.

**Comment by Rodrxx** [comment] 2021-11-15 17:45
There are 2 options that i know in task scheduler by now, the first one and most common, is to just launch the app just after i login into the desktop (just like any other app does, like discord, steam, etc.), the second one is just launch the app as soon as the laptop boots up, i dont know in which level of hierarchy does this thing loads, but in order to launch the app before the login i have to enter administrator credentials,i just wanted to do that just for the looks to have the custom lightning effect right after the keyboard lights turns on, maybe a more secure launch option to open like every other app with the windows login can be handy

**Comment by 4JX** [comment] 2021-11-15 17:50
> There are 2 options that i know in task scheduler by now, the first one and most common, is to just launch the app just after i login into the desktop (just like any other app does, like discord, steam, etc.), the second one is just launch the app as soon as the laptop boots up, i dont know in which level of hierarchy does this thing loads, but in order to launch the app before the login i have to enter administrator credentials,i just wanted to do that just for the looks to have the custom lightning effect right after the keyboard lights turns on, maybe a more secure launch option to open like every other app with the windows login can be handy

Support for launching via task scheduler is planned (though I haven't investigated how well that'll work yet). I'll probably opt to launch after login just in case.

Will leave this issue up until I can either confirm it was not the program that broke things or I properly implement it.

**Comment by 4JX** [comment] 2021-11-29 16:13
Tested without issues on https://github.com/4JX/L5P-Keyboard-RGB/issues/33#issuecomment-981784483. Will close this until another case pops up.

**Closed by 4JX** 2021-11-29 16:13 UTC
